/**
 * data.js — Olivia's personal anime recommendations dataset
 *
 * This file contains only data, no logic!
 * I learned this separation makes testing and updating way easier.
 * Each anime has 8 properties that my filters can check against.
 *
 * Prof. Teeters reminded me: "Data lives here. Logic lives in matching.js. DOM lives in app.js."
 */

const data = {
  domain: 'Anime',
  description:
    'Find the perfect anime based on genre, mood, language preference, and viewing time',
  options: [
    // ACTION ANIME
    // These are my go-to high-energy shows!
    {
      name: 'Demon Slayer',
      genre: 'action',
      mood: 'intense',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'ongoing',
      episodeCount: 55,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'My Hero Academia',
      genre: 'action',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'ongoing',
      episodeCount: 138,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Attack on Titan',
      genre: 'action',
      mood: 'dark',
      audioLanguage: 'both',
      rating: 'mature',
      completionStatus: 'completed',
      episodeCount: 87,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'One Punch Man',
      genre: 'action',
      mood: 'lighthearted',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'ongoing',
      episodeCount: 24,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Jujutsu Kaisen',
      genre: 'action',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'ongoing',
      episodeCount: 47,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Fullmetal Alchemist: Brotherhood',
      genre: 'action',
      mood: 'emotional',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 64,
      episodeLengthMinutes: 24,
      userRating: 5,
    },

    // ROMANCE ANIME
    // Perfect for emotional moments!
    {
      name: 'Your Name',
      genre: 'romance',
      mood: 'emotional',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 1,
      episodeLengthMinutes: 107,
      userRating: 5,
    },
    {
      name: 'Toradora!',
      genre: 'romance',
      mood: 'lighthearted',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 25,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Horimiya',
      genre: 'romance',
      mood: 'uplifting',
      audioLanguage: 'sub',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 13,
      episodeLengthMinutes: 24,
      userRating: 4,
    },
    {
      name: 'Kaguya-sama: Love is War',
      genre: 'romance',
      mood: 'lighthearted',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 37,
      episodeLengthMinutes: 24,
      userRating: 5,
    },

    // COMEDY ANIME
    // When I just need to laugh!
    {
      name: 'Spy x Family',
      genre: 'comedy',
      mood: 'lighthearted',
      audioLanguage: 'both',
      rating: 'kids',
      completionStatus: 'ongoing',
      episodeCount: 37,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'The Disastrous Life of Saiki K.',
      genre: 'comedy',
      mood: 'lighthearted',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 120,
      episodeLengthMinutes: 5,
      userRating: 5,
    },
    {
      name: 'Ouran High School Host Club',
      genre: 'comedy',
      mood: 'lighthearted',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 26,
      episodeLengthMinutes: 24,
      userRating: 4,
    },
    {
      name: 'Gintama',
      genre: 'comedy',
      mood: 'exciting',
      audioLanguage: 'sub',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 367,
      episodeLengthMinutes: 24,
      userRating: 5,
    },

    // HORROR ANIME
    // For when I want to be scared!
    {
      name: 'Another',
      genre: 'horror',
      mood: 'dark',
      audioLanguage: 'both',
      rating: 'mature',
      completionStatus: 'completed',
      episodeCount: 12,
      episodeLengthMinutes: 24,
      userRating: 4,
    },
    {
      name: 'Parasyte',
      genre: 'horror',
      mood: 'intense',
      audioLanguage: 'both',
      rating: 'mature',
      completionStatus: 'completed',
      episodeCount: 24,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Tokyo Ghoul',
      genre: 'horror',
      mood: 'dark',
      audioLanguage: 'both',
      rating: 'mature',
      completionStatus: 'completed',
      episodeCount: 48,
      episodeLengthMinutes: 24,
      userRating: 4,
    },

    // SLICE-OF-LIFE ANIME
    // These are so calming and wholesome!
    {
      name: 'March Comes in Like a Lion',
      genre: 'slice-of-life',
      mood: 'emotional',
      audioLanguage: 'sub',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 44,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Non Non Biyori',
      genre: 'slice-of-life',
      mood: 'relaxing',
      audioLanguage: 'sub',
      rating: 'kids',
      completionStatus: 'completed',
      episodeCount: 36,
      episodeLengthMinutes: 24,
      userRating: 4,
    },
    {
      name: 'Barakamon',
      genre: 'slice-of-life',
      mood: 'uplifting',
      audioLanguage: 'both',
      rating: 'kids',
      completionStatus: 'completed',
      episodeCount: 12,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'K-On!',
      genre: 'slice-of-life',
      mood: 'lighthearted',
      audioLanguage: 'both',
      rating: 'kids',
      completionStatus: 'completed',
      episodeCount: 41,
      episodeLengthMinutes: 24,
      userRating: 4,
    },

    // FANTASY ANIME
    // Magical worlds and adventures!
    {
      name: 'Spirited Away',
      genre: 'fantasy',
      mood: 'uplifting',
      audioLanguage: 'both',
      rating: 'kids',
      completionStatus: 'completed',
      episodeCount: 1,
      episodeLengthMinutes: 125,
      userRating: 5,
    },
    {
      name: "Frieren: Beyond Journey's End",
      genre: 'fantasy',
      mood: 'emotional',
      audioLanguage: 'sub',
      rating: 'teen',
      completionStatus: 'ongoing',
      episodeCount: 28,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Fairy Tail',
      genre: 'fantasy',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 328,
      episodeLengthMinutes: 24,
      userRating: 4,
    },
    {
      name: 'Magi: The Labyrinth of Magic',
      genre: 'fantasy',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 50,
      episodeLengthMinutes: 24,
      userRating: 4,
    },

    // SCI-FI ANIME
    // Future tech and time travel!
    {
      name: 'Steins;Gate',
      genre: 'sci-fi',
      mood: 'intense',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 24,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Cowboy Bebop',
      genre: 'sci-fi',
      mood: 'relaxing',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 26,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Psycho-Pass',
      genre: 'sci-fi',
      mood: 'dark',
      audioLanguage: 'both',
      rating: 'mature',
      completionStatus: 'completed',
      episodeCount: 41,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Dr. Stone',
      genre: 'sci-fi',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'ongoing',
      episodeCount: 58,
      episodeLengthMinutes: 24,
      userRating: 5,
    },

    // THRILLER ANIME
    // Edge-of-your-seat suspense!
    {
      name: 'Death Note',
      genre: 'thriller',
      mood: 'intense',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 37,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Monster',
      genre: 'thriller',
      mood: 'dark',
      audioLanguage: 'sub',
      rating: 'mature',
      completionStatus: 'completed',
      episodeCount: 74,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Erased',
      genre: 'thriller',
      mood: 'emotional',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 12,
      episodeLengthMinutes: 24,
      userRating: 4,
    },

    // SPORTS ANIME
    // These get me so pumped up!
    {
      name: 'Haikyuu!!',
      genre: 'sports',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'kids',
      completionStatus: 'completed',
      episodeCount: 85,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: "Kuroko's Basketball",
      genre: 'sports',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 75,
      episodeLengthMinutes: 24,
      userRating: 4,
    },
    {
      name: 'Run with the Wind',
      genre: 'sports',
      mood: 'uplifting',
      audioLanguage: 'sub',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 23,
      episodeLengthMinutes: 24,
      userRating: 5,
    },

    // MECHA ANIME
    // Giant robots FTW!
    {
      name: 'Neon Genesis Evangelion',
      genre: 'mecha',
      mood: 'dark',
      audioLanguage: 'both',
      rating: 'mature',
      completionStatus: 'completed',
      episodeCount: 26,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Code Geass',
      genre: 'mecha',
      mood: 'intense',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 50,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Gurren Lagann',
      genre: 'mecha',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 27,
      episodeLengthMinutes: 24,
      userRating: 5,
    },

    // ISEKAI ANIME
    // Transported to another world!
    {
      name: 'Re:Zero',
      genre: 'isekai',
      mood: 'dark',
      audioLanguage: 'both',
      rating: 'mature',
      completionStatus: 'ongoing',
      episodeCount: 50,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Konosuba',
      genre: 'isekai',
      mood: 'lighthearted',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 20,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'That Time I Got Reincarnated as a Slime',
      genre: 'isekai',
      mood: 'uplifting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'ongoing',
      episodeCount: 72,
      episodeLengthMinutes: 24,
      userRating: 4,
    },
    {
      name: 'Sword Art Online',
      genre: 'isekai',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'ongoing',
      episodeCount: 96,
      episodeLengthMinutes: 24,
      userRating: 4,
    },

    // SUPERNATURAL ANIME
    // Ghosts, spirits, and special powers!
    {
      name: 'Mob Psycho 100',
      genre: 'supernatural',
      mood: 'uplifting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 37,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
    {
      name: 'Noragami',
      genre: 'supernatural',
      mood: 'exciting',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'hiatus',
      episodeCount: 25,
      episodeLengthMinutes: 24,
      userRating: 4,
    },
    {
      name: 'The Promised Neverland',
      genre: 'supernatural',
      mood: 'intense',
      audioLanguage: 'both',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 23,
      episodeLengthMinutes: 24,
      userRating: 4,
    },
    {
      name: 'Mushishi',
      genre: 'supernatural',
      mood: 'relaxing',
      audioLanguage: 'sub',
      rating: 'teen',
      completionStatus: 'completed',
      episodeCount: 46,
      episodeLengthMinutes: 24,
      userRating: 5,
    },
  ],
};

// I learned this export syntax makes the data available to other files!
// Prof. Teeters explained: "Think of export as sharing your data with the rest of your app"
export { data };
